const express=require('express')
const router=express.Router()
const {createTask,getTasks,getTaskById, updateTask,updateTaskPatch,deleteTask}=require('../controllers/taskControllers')
const {protect}=require('../Middleware/authmiddleware')
router.post('/newTask',protect,createTask)
router.get('/getTasks',protect,getTasks)
router.get('/getTaskById/:id',protect,getTaskById)
router.put('/updateTask/:id',protect,updateTask)
router.patch('/updateTaskPatch/:id',protect,updateTaskPatch)
router.delete('/deleteTask/:id',protect,deleteTask)
module.exports=router